apiVersion: v1
kind: Service
metadata:
  name: thegamebazar-service
spec:
  selector:
    app: thegamebazar
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thegamebazar
spec:
  selector:
    matchLabels:
      app: thegamebazar
  replicas: 2
  template:
    metadata:
      labels:
        app: thegamebazar
    spec:
      containers:
      - name: thegamebazar
        image: thegamebazar:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
